version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword123
      MYSQL_DATABASE: expenses
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - 3306:3306